### PR TITLE
Adding bootstrap based template.

### PR DESCRIPTION
**Pull request by pserwylo**
I think this is ready to merge now.

For the most part, it is completely responsive. There may be some parts where it doesn't quite work out, and my hope is that this can get worked on into the future. There is some javascript, but the webiste will be just as usable without javascript enabled.

I also added a new string to lang.php for "Past Versions". To fill in the other languages, I used Google Translate. I realise this is not perfect, so you may want to run an eye over the French translation and any other languages you may know :)

I haven't tested the accessibility of it - but it is not the default theme, so hopefully it is not as much an issue as it was with the previous PR. I'm happy to look into any issues people log against it if they choose to use this theme, and then submit relevant PR. But for now, I'm pretty happy with how it all works.

### CODE REVIEW

**Comment by pserwylo** [comment]
Oh, I didn't check the .htaccess changes, because I was serving using the PHP local server, not apache. But I added a rule (copied and pasted from the magical internet) to prevent access to .tpl files through apache. Hopefully it works as expected (not the end of the world if it doesn't - they are all open source template files available in this repo).

**Comment by dervishe-** [comment]
Well done, very nice work :D 
I have just added a cursor: pointer on the collapse button because on firefox it was difficult to use it.
Just few things:
- i think there is a little trouble with the header: (look at the image i posted here)
  As you can see, there's a little kind of "offset" in the description description, perhaps, we could fixe the image size of the logo in the css ? And if the title is a little bit long, there's a trouble with the "cut". Perhaps we can vertiacally align the logo, the title and the qr-code. What you think ?
  bootstrap_head
- There is some issues with the HTML5 validation, but i will check this. For tha accessibility, there's some issue but i think i will be easy to fix. (I will try that and let you know)

Perhaps, we could put a theme selector, thus, visitors can use the theme they prefer.

All this said, again well done :)

By the way, i added you on the README first page but you didn't credit your work in the template, you can add a README page with your credit and license in it ;)

**Comment by dervishe-** [comment]
I have made several slight modifications to ensure html5 validation. In this order i put some missing h2 in articles with style="position:absolute; top:-1000px" but i'm not very found of style attibutes in html code. Perhap's we can creat a .hide class with same purpose (I don't use display:none or this sort of things because it break the accessibility rules)
In this case, perhaps we can get ride of all the style attribute and migrate them to few css class.
Also  i added cursor:pointer in a style attribute for the titles of Licenses, Categories, Search and Last App.
Perhaps you can send me your non minified css file (i'm a little bit lazy to use the minified one ;) )

**Comment by dervishe-** [comment]
I put some [issues](https://github.com/dervishe-/f-droid-web/issues) regarding the bootstrap theme and the templating system

**Pull request merged**
